//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContactListEFCRUD
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactList
    {
        public int Id { get; set; }
        public string FName2 { get; set; }
        public string Surname { get; set; }
        public string Company { get; set; }
        public string Number { get; set; }
        public string Adress { get; set; }
    }
}
